In [1]:
import pandas as pd

df = pd.read_csv("retail_sales.csv")
print("Dataset loaded")

# .head() prints first 5 rows of the dataset
df.head()

Dataset loaded

,Order_ID,Date,Customer,City,Product,Category,Quantity,Price,Payment_Mode,Rating
0,1001,2024-01-01,Amit,NaN,Laptop,Electronics,1,65000,Card,5.0
1,1002,2024-01-02,Riya,Delhi,Headphones,Electronics,2,2000,UPI,NaN
2,1003,2024-01-03,Arjun,Mumbai,Keyboard,Electronics,1,1500,Card,4.0
3,1004,2024-01-04,Priya,Bangalore,Chair,Furniture,1,4500,Cash,5.0
4,1005,2024-01-05,Rohit,Pune,Table,Furniture,1,7000,UPI,4.0

In [2]:
print("Dataset shape: ")
print(df.shape)

print("\ncol names: ")
print(df.columns)

# Jupyter automatically displays the value of the last expression in a cell, but not previous expressions unless you explicitly print them.
print("\nData types: ")
df.dtypes

Dataset shape:
(60, 10)

col names:
Index(['Order_ID', 'Date', 'Customer', 'City', 'Product', 'Category',
       'Quantity', 'Price', 'Payment_Mode', 'Rating'],
      dtype='str')

Data types:

Order_ID          int64
Date                str
Customer            str
City                str
Product             str
Category            str
Quantity          int64
Price             int64
Payment_Mode        str
Rating          float64
dtype: object

In [3]:
# selecting single col

# prints the col without the header
df["Order_ID"]

0     1001
1     1002
2     1003
3     1004
4     1005
5     1006
6     1007
7     1008
8     1009
9     1010
10    1011
11    1012
12    1013
13    1014
14    1015
15    1016
16    1017
17    1018
18    1019
19    1020
20    1021
21    1022
22    1023
23    1024
24    1025
25    1026
26    1027
27    1028
28    1029
29    1030
30    1031
31    1032
32    1033
33    1034
34    1035
35    1036
36    1037
37    1038
38    1039
39    1040
40    1041
41    1042
42    1043
43    1044
44    1045
45    1046
46    1047
47    1048
48    1049
49    1050
50    1051
51    1052
52    1053
53    1054
54    1055
55    1056
56    1057
57    1058
58    1059
59    1060
Name: Order_ID, dtype: int64

In [4]:
# displays the col along with header
df[["Order_ID"]]

# displays the last 5 records
df[["Order_ID"]].tail()

    Order_ID
55      1056
56      1057
57      1058
58      1059
59      1060

In [5]:
# selecting multiple cols
df[["Order_ID","Date","Customer","City"]].tail()

    Order_ID        Date Customer       City
55      1056  2024-02-26    Payal      Delhi
56      1057  2024-02-27    Omkar     Mumbai
57      1058  2024-02-28   Sanjay  Bangalore
58      1059  2024-02-29    Megha       Pune
59      1060  2024-03-01    Kiran    Chennai

In [6]:
print("filtering data with single filter: ")
electronics = df[df["Category"] == "Electronics"]
electronics.head()

filtering data with single filter:

,Order_ID,Date,Customer,City,Product,Category,Quantity,Price,Payment_Mode,Rating
0,1001,2024-01-01,Amit,NaN,Laptop,Electronics,1,65000,Card,5.0
1,1002,2024-01-02,Riya,Delhi,Headphones,Electronics,2,2000,UPI,NaN
2,1003,2024-01-03,Arjun,Mumbai,Keyboard,Electronics,1,1500,Card,4.0
5,1006,2024-01-06,Sneha,Chennai,Monitor,Electronics,1,12000,Card,5.0
6,1007,2024-01-07,Ankit,Kolkata,Mouse,Electronics,2,800,UPI,4.0

In [7]:
print("filtering data with multiple filter: ")

# when using multiple filters, enclose each filter in '()'
filtered_df = df[(df["Price"]>10000) & (df["Category"] == "Electronics")]

# to display the first 4 elements
filtered_df.head(4)

filtering data with multiple filter:

,Order_ID,Date,Customer,City,Product,Category,Quantity,Price,Payment_Mode,Rating
0,1001,2024-01-01,Amit,NaN,Laptop,Electronics,1,65000,Card,5.0
5,1006,2024-01-06,Sneha,Chennai,Monitor,Electronics,1,12000,Card,5.0
12,1013,2024-01-13,Aisha,Kolkata,Laptop,Electronics,1,70000,Card,5.0
17,1018,2024-01-18,Aditya,Chennai,Monitor,Electronics,1,13000,Card,5.0

In [8]:
# Adding new col
df["Total_Sales"] = df["Quantity"] * df["Price"]
df.head(2)

,Order_ID,Date,Customer,City,Product,Category,Quantity,Price,Payment_Mode,Rating,Total_Sales
0,1001,2024-01-01,Amit,NaN,Laptop,Electronics,1,65000,Card,5.0,65000
1,1002,2024-01-02,Riya,Delhi,Headphones,Electronics,2,2000,UPI,NaN,4000

In [9]:
# Sorting data

# ascending by default
# sorted_df = df.sort_values(by="Price")

# descending
sorted_df = df.sort_values(by="Price", ascending = False)
sorted_df.head(10)

,Order_ID,Date,Customer,City,Product,Category,Quantity,Price,Payment_Mode,Rating,Total_Sales
56,1057,2024-02-27,Omkar,Mumbai,Laptop,Electronics,1,75000,Card,5.0,75000
38,1039,2024-02-09,Sahil,Mumbai,Laptop,Electronics,1,72000,Card,5.0,72000
12,1013,2024-01-13,Aisha,Kolkata,Laptop,Electronics,1,70000,Card,5.0,70000
24,1025,2024-01-25,Nisha,Kolkata,Laptop,Electronics,1,68000,UPI,5.0,68000
0,1001,2024-01-01,Amit,NaN,Laptop,Electronics,1,65000,Card,5.0,65000
17,1018,2024-01-18,Aditya,Chennai,Monitor,Electronics,1,13000,Card,5.0,13000
30,1031,2024-02-01,Anjali,Kolkata,Monitor,Electronics,1,12500,UPI,5.0,12500
5,1006,2024-01-06,Sneha,Chennai,Monitor,Electronics,1,12000,Card,5.0,12000
48,1049,2024-02-19,Aakash,Kolkata,Monitor,Electronics,1,11800,UPI,4.0,11800
31,1032,2024-02-02,Rakesh,Delhi,Printer,Electronics,1,9800,Card,4.0,9800

In [10]:
# Handling missing values
df.head().isnull()

,Order_ID,Date,Customer,City,Product,Category,Quantity,Price,Payment_Mode,Rating,Total_Sales
0,False,False,False,True,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,True,False
2,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False

In [11]:
# unique values
df["City"].unique()

<StringArray>
[nan, 'Delhi', 'Mumbai', 'Bangalore', 'Pune', 'Chennai', 'Kolkata']
Length: 7, dtype: str

In [12]:
# frequency
df["Category"].value_counts()

Category
Electronics    32
Furniture      16
Stationery     12
Name: count, dtype: int64

In [ ]:
# group by operation
grouped = df.groupby("Category")
max_sales = grouped["Total_Sales"].max()
max_sales

Category
Electronics    75000
Furniture       8900
Stationery       690
Name: Total_Sales, dtype: int64

In [21]:
# multiple aggregations
sales = df.groupby("City")["Total_Sales"].agg(["max", "min", "sum"])
sales

             max   min     sum
City
Bangalore   8900   440   58830
Chennai    13000  1560   66160
Delhi       9800   200   37736
Kolkata    70000   375  174195
Mumbai     75000   200  186160
Pune        9300   216   44224

In [ ]:
# index = rows
# columns = columns
# values = numbers to calculate
# aggfunc = calculation to perform

pivot = pd.pivot_table(
    df,
    values="Total_Sales",
    index="City",
    columns="Category",
    aggfunc="sum"
)
pivot

Category   Electronics  Furniture  Stationery
City
Bangalore      18500.0    39200.0      1130.0
Chennai        42860.0    23300.0         NaN
Delhi          27600.0     8400.0      1736.0
Kolkata       163900.0     8800.0      1495.0
Mumbai        162160.0    23800.0       200.0
Pune           32700.0    11000.0       524.0

In [27]:
df["Date"] = pd.to_datetime(df["Date"]).dt.month
df["Date"]

0     1
1     1
2     1
3     1
4     1
5     1
6     1
7     1
8     1
9     1
10    1
11    1
12    1
13    1
14    1
15    1
16    1
17    1
18    1
19    1
20    1
21    1
22    1
23    1
24    1
25    1
26    1
27    1
28    1
29    1
30    2
31    2
32    2
33    2
34    2
35    2
36    2
37    2
38    2
39    2
40    2
41    2
42    2
43    2
44    2
45    2
46    2
47    2
48    2
49    2
50    2
51    2
52    2
53    2
54    2
55    2
56    2
57    2
58    2
59    3
Name: Date, dtype: int32

In [30]:
# export processed data

df.to_csv("Processed_sales.csv", index=False)